name: Modify IPA

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs: 
      app:
        description: The location of the IPA file to patch
        required: true
      tweaks:
        description: The locations or bundle ids of the tweaks to inject
      version:
        description: Custom version for app
      display-name:
        description: Custom display name for app
      name:
        description: Custom name for app
      support-devices:
        type: boolean
        description: Remove UISupportedDevices from app (Support more devices)

jobs:
  modify:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Initialize
        run: mkdir ./output

      - name: Azule
        run: |
          if [ ${{ inputs.tweaks }} != '' ]
          then
            tweaksparam='-f ${{ inputs.tweaks }}'
          fi
          if [ ${{ inputs.version }} != '' ]
          then
            versionparam='-c ${{ inputs.version }}'
          fi
          if [ ${{ inputs.display-name }} != '' ]
          then
            displaynameparam='-f ${{ inputs.displayname }}'
          fi
          if [ ${{ inputs.name }} != '' ]
          then
            nameparam='-f ${{ inputs.name }}'
          fi
          if [ ${{ inputs.support-devices }} == 'true' ]
          then
            supportdevicesparam='-u'
          fi
          ./azule -i ${{ inputs.app }} -o ./output $tweaksparam $versionparam $displaynameparam $nameparam $supportdevicesparam
        
      - uses: actions/upload-artifact@v3
        with:
          name: patched-ipa
          path: output/*.ipa
